Server:
  port: ${PORT}
spring:
  autoconfigure:
    exclude: ${EXCLUDE}
  data:
    mongodb:
      uri:  ${URI}
  activemq:
    broker-url: $BROKEN_URI}
    user: ${USER}
    password: ${PASSWORD}  
message:
  outbound:
    hugoWithoutJMQueue: ${QUEUE}
mipres:
  default:
    juntaMedicaUrl: ${JUNTAMEDICAURL}